{% set version = "1.7.1" %}

package:
  name: pep8
  version: {{ version }}

source:
  fn: pep8-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pep8/pep8-{{ version }}.tar.gz
  sha256: fe249b52e20498e59e0b5c5256aa52ee99fc295b26ec9eaa85776ffdb9fe6374

build:
  entry_points:
    - pep8 = pep8:_main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - pep8 --help
    - pep8 --version

about:
  home: http://pep8.readthedocs.org/
  license: MIT
  summary: 'Python style guide checker'

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - jjhelmus
