travis:
  secure:
    BINSTAR_TOKEN: FquVn/TYgJFzH6pSANHrIjjBoJwP8qgmhaKJux56bA+LSlOvWj3tphHZShsDJXdLUjNy7sglUdVsOvT9GsKpK73ZuEqdmgMziuPRmG2EEZVq/ViZikOEUvXmAq05ZZp6TwcSuDE4GvpMnH/djk2iHqXJnB4Lwzqdrnrz3FQuoqTAnEJGkAERTAm8dafPDq1b7iOtqwVGghToryuIUJGSOHdok7veBE4DTm4EYKaHAZwCHvB5CJTtOclCuyaBFKSMP9twfT3DreJHlX3zY+O5UbymiW+WncoOWinUFrZT3t9vLN4KG3Xnt+wgo5l3Du5xd4g0EQV+Z+chNgRFIiV1Kbwm5emXTiNrwj8NqQIetn1kYX5aq88lcMik2IBpvmel9lzaXvpCz4KHm+NfGpcB3KZ2Py2Mn709VD8/8GhqMZL82DCFJFs19CdlcRAzfhkS8mBqgCjKjvY1lapo9ZO66dQ8KcKf8wkASNLQ3e6Yc9eJFgZ5P95RY9t5OaUSPnAxgcim1n9QL2+d/JOYDX1VZ4UXM9yt+jlIkbI2tNXfjqaFNEE7r7t3s82GJB8gObAc0oo0Ag0rHF1QanCBtK4FjN/jNgou4627cLrKGlZfYQqoJGQ4ELPwHSIVvCvWQnx0q0JldZWJPfX2G6pykCeLtKKZQj79E5gQmiOaVgQvIzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
