travis:
  secure:
    BINSTAR_TOKEN: a13QhVimqtyKsYbo5x5EcduW0G62BuUjLS7FlrBIFRyi3dJUa8RPpkgAQB+pXNxBmPdOAeNp4in0VS61vXVIOYGvdZof/X3BUjGepcoxFidysP1aEc0YfUFt8LizgMo5BTh2k++aSV2bf0ZwE0G/64PAR/Tc+1E+/ky0vmbijJILq0dQKv1qqICCrgz/65dyONOfPfIo18FVjZDaGYwX5uXNvP3hAlEGJiay00OR1d8QFXLXlBZBKQ3/a5MJ6NeK6eAgMWV+hAWE245aCuujUcFw9JFoL55uS3WAXMMKnvBaHf9eMAJ7MY2Ev6J3JOTwvKKJ30IY9rewn8Q0AtzaqrmJJBmqSCGMyZWUeCz0pXPe51/TH6KkyVhia1t1MeqVLVHflTajrurs0i4nhy2Q9qx1R0Fs06xEFsu3UJHkuPWOPPBrNZr73X5PswCz/yIiAcW2rOiLL44JHFx6UEc0tyJBs+5DBoYe2g3jfdAV4Jm/Tb6NBH9n+BACbASYDhYVcF46eBgGoK8785713fj8Gl7upt4AHQYOzWG8+JjPI8WSmcC8fCab0rV6atJLU8TiAvfIw4ejyJ5qu5db4u5eDPD20S73TBFkvowLwTC6TKDfbQsNF048GYaBOV06UsKlZQY4Z/LKJ8x2PkTWmdlhs0rE+9wGhdUleMZ7p4IaFcg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
